### ISSUE TITLE
XamlCombine is not working with UWP/WinUI

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#47]
Hi @batzen 
In UWP/WinUI we have different types that we can use in the ResourceDictionary for example:

`
{ThemeResource resource}
`

`<ThemeShadow Name="theme"/>
`
or

```
<ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Dark">
<StaticResource x:Key="CardBackgroundBrush" ResourceKey="CardBackgroundFillColorDefaultBrush" />
            <StaticResource x:Key="CardBorderBrush" ResourceKey="CardStrokeColorDefaultBrush" />
            <StaticResource x:Key="CardPrimaryForegroundBrush" ResourceKey="TextFillColorPrimaryBrush" />
            <SolidColorBrush x:Key="InfoBarInformationalSeverityBackgroundBrush" Color="#FF34424d"/>
            <Color x:Key="InfoBarInformationalSeverityIconBackground">#FF5fb2f2</Color>
            <Thickness x:Key="CardBorderThickness">1</Thickness>
        </ResourceDictionary>

        <ResourceDictionary x:Key="Light">
...
        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast">
...
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
```

can you please update xamlcombine for supporting this?

**Comment by batzen** [comment]
Could you add sample input files and the expected output? I haven't used UWP/WinUI yet, and most likely will never use it.

**Comment by ghost1372** [comment]
thank you
~~this is my repo
https://github.com/ghost1372/SettingsUI/tree/main/src/SettingsUI/Themes~~

~~I am currently using the old version of xamlcombine with some modifications I made myself.
Is this sample enough or do I need to attach another sample?~~

[Colors.xaml](https://github.com/ghost1372/SettingsUI/blob/main/src/SettingsUI/Themes/Styles/Colors.xaml) and
[Common.xaml](https://github.com/ghost1372/SettingsUI/blob/main/src/SettingsUI/Themes/Styles/Common.xaml)
can not be merged into generic.xaml because of **<ThemeShadow** and **ThemeDictionary**

**Comment by ghost1372** [comment]
try this sample
[App16.zip](https://github.com/batzen/XAMLTools/files/8935601/App16.zip)

**Comment by ghost1372** [comment]
also why this line is generating in my resourcedictionary? `**<?xml version="1.0" encoding="utf-8"?>**`

**Comment by ghost1372** [comment]
i tested with microsoft [combiner](https://github.com/microsoft/microsoft-ui-xaml/blob/main/tools/CustomTasks/MergedDictionary.cs) and it is working fine. mybe this can help

**Comment by ghost1372** [comment]
@batzen Can you fix this issue a little sooner? Or at least announce its approximate time

**Comment by ghost1372** [comment]
Thank you @batzen for fixing this issue.
Can you update nuget package?

**Comment by batzen** [comment]
Will upload a new version later today.

**Comment by batzen** [comment]
Done.
