### ISSUE TITLE
Add Comment for combined xaml

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#48]
Is there a way to add a comment message at the top of the combined xaml file?
I want to add a message like the one below at the top of the file

```
<!--
    This code was generated by a tool.
    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
-->
```

If not, can you provide it?
tnx

**Comment by batzen** [comment]
Very good suggestion.
Will add this and also the list of source files that were combined.

**Comment by ghost1372** [comment]
Thank you, It would be great if we could set the message with a property something like this
```
<CommentMessage>This code was generated by a tool.</CommentMessage>
<ShowSourceFiles>True</ShowGeneratedFiles>
```
