### ISSUE TITLE
Resources Order Issue

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#49]
I used XamlTools in a Large Repo, The problem is that resources depend on each other, first of all i tried this way

```
<XAMLCombineItems Include="$(RootPath)\Styles\*.xaml">
      <TargetFile>$(ThemePath)</TargetFile>
    </XAMLCombineItems>
```
After running the program, I encountered the following error

> Exception: Cannot find resource named 'NavigationWindowBaseStyle'. Resource names are case sensitive.

But when I look at the theme file, this style is available

![1](https://user-images.githubusercontent.com/9213496/174587174-9093d78e-6e1d-41d3-ad3c-6a49ef806a3e.png)

So the problem is the order of resources.
I tried to specify the order of resources through the following method, But the result was the same and I get the same error again

```
<XAMLCombineItems Include="
                      $(RootPath)\Styles\BlendEffectBox.xaml;
                      $(RootPath)\Styles\Border.xaml;
                      $(RootPath)\Styles\Col.xaml;
                       .................
                      $(RootPath)\Styles\AutoCompleteTextBox.xaml;">
      <TargetFile>$(ThemePath)</TargetFile>
    </XAMLCombineItems>
```

**Comment by batzen** [comment]
Could you add a small repro for this?
This looks like a bug in the usage detection for resource keys.

I added a test to verify correct ordering for the cases that are recognized and it verifies that the current logic works correctly for those cases.

**Comment by ghost1372** [comment]
tnx
[src.zip](https://github.com/batzen/XAMLTools/files/9061002/src.zip)

**Comment by batzen** [comment]
Can't reproduce that issue after fixing the csproj.

Just had to replace
```
    <XAMLCombineItems Include="..\..\Shared\HandyControl_Shared\Themes\Styles\*.xaml">
      <TargetFile>..\..\Shared\HandyControl_Shared\Themes\Theme.xaml</TargetFile>
    </XAMLCombineItems>
```

with

```
    <XAMLCombineItems Include="..\..\Shared\HandyControl_Shared\Themes\Styles\**\*.xaml">
      <TargetFile>..\..\Shared\HandyControl_Shared\Themes\Theme.xaml</TargetFile>
    </XAMLCombineItems>
```

**Comment by ghost1372** [comment]
@batzen Tnx. I will test it.
What does ** mean?

**Comment by batzen** [comment]
** = any subfolder

**Comment by ghost1372** [comment]
tnx issue fixed🙏
