### ISSUE TITLE
Namespace replacement not working correctly with combine items

### ISSUE THREAD

**Issue by Nuklon** [batzen/XAMLTools#52]
Example:

File1:
```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:controls="clr-namespace:WPF.Controls">

      <DataTemplate x:Key="Test">
        <ScrollViewer Name="ScrollViewer">
        </ScrollViewer>
        <DataTemplate.Triggers>
            <DataTrigger Binding="{Binding SomeBinding}"
                         Value="True">
                <Setter TargetName="ScrollViewer" Property="MaxHeight" Value="{Binding Path=(controls:Parameters.MaxHeight), Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType=ListBox}}" />
            </DataTrigger>
        </DataTemplate.Triggers>
    </DataTemplate>

</ResourceDictionary>
```

File2, note that controls has a different namespace and that also the used type is different:

```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:controls="clr-namespace:ANOTHER_NAMESPACE.Controls">

      <DataTemplate x:Key="AnotherTest">
        <ScrollViewer Name="ScrollViewer">
        </ScrollViewer>
        <DataTemplate.Triggers>
            <DataTrigger Binding="{Binding SomeBinding}"
                         Value="True">
                <Setter TargetName="ScrollViewer" Property="MaxHeight" Value="{Binding Path=(controls:OtherParameters.MaxHeight), Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType=ListBox}}" />
            </DataTrigger>
        </DataTemplate.Triggers>
    </DataTemplate>

</ResourceDictionary>
```

In merged file, the second **controls** namespace gets renamed to controls_0, but not inside the xaml, so you'll end up with an invalid type (the OtherParameters namespace is still at **controls**).

**Comment by batzen** [comment]
After thinking about this a lot and trying to get it completely right i decided to just throw an error for the offending duplicates and files causing the duplicates.
It's way easier to just fix the duplicate in the source files than to try to rename everything properly.

**Comment by Nuklon** [comment]
I have quite some XAMLs so it would be quite a lot to rename, especially when VS always creates these names as default. Are there really that many possiblities to replace? I think ```(<|()ANOTHER_NAMESPACE:``` (regex) would suffice?

**Comment by batzen** [comment]
I would only throw for duplicates with the same name but different namespace value.

Could you point me to your project that would be affected, or is it private?

Getting the replacement right for everything is hard and complicated. What if some uses "xy:" just as text? What if someone parses or reads or correlate (to the original files) the XAML and expects everything unchanged?

Throwing an error for conflicting names, on the other hand, is easy and requires minimal work to fix.

**Comment by Nuklon** [comment]
It's a private project unfortunately.
If you check for existence of <, this isn't allowed as text/value (gives an error), so <controls: would be the only possibility. With regards to (controls:, that's only allowed within { } I think, which isn't valid as text either (also gives an error).
So a Regex replacement for the first case would be:
```
<(controls):
Replace with:
<controls_1:
```
And for the second case would be:
```
\"{(.*)\(controls:(.*)}\"
Replace with:
\"{$1(controls_1:$2}\"
```
If someone parses XAML then I'm not sure they would use this project as it can already transform the XAML.

**Comment by batzen** [comment]
It's more complicated than that.
A few samples:
- `{Binding Path=(controls:Parameters.MaxHeight)}`
- `{Binding Path=controls:Parameters.MaxHeight}`
- `Setter Property="controls:Parameters.MaxHeight"`
- `TargetType="{x:Type controls:TextBox}"`

So, there is no requirement for neither "{}" nor "()" being present.

> If someone parses XAML then I'm not sure they would use this project as it can already transform the XAML.

There are no other transformations that alter the content, it's only re-ordering.

I think it's just too dangerous and error prone to try to cover all cases while still supporting XAML (not only WPF).
The error message being thrown will contain the offending namespaces and the files that are causing the error.
I am sorry if this causes some work on your side.

**Comment by Nuklon** [comment]
In three of your examples there's { } present. The regex above is quite strict but can be relaxed a little: 
```
\"{(.*)(\(?)controls:(.*)}\"
to
\"{$1$2controls_1:$3}\"
```

You're right about ```Setter Property```, I totally forgot about that one. That too wouldn't be too bad to check though, ```Property=\"controls:(\w+)\.(\w+)\"```

Perhaps something like this can be put behind an option? Such as ```TryReplaceDuplicateNamespaces```?

**Comment by batzen** [comment]
Then there is also 
- `xyz:ABC.XX="something"`
- `TargetType="local:ToggleButtonEx"`

So, basically the regex would have to be `namespace:(\w+)`, which means if someone uses `Description="Controls:MyControl can be used as a starting point"` it would get replaced.

It's just too error prone to try being fully correct here.
And as i said it's very easy to fix all conflicts in the source files.

I just pushed the new version to nuget.
Maybe you can try that and see how many errors you get.

There is also a new warning about duplicate keys and elements without keys.

**Comment by Nuklon** [comment]
There are indeed quite a lot edge cases so I guess an error is probably the easier way. I've tried the latest version and had to change namespaces in about 20 files, which wasn't too bad.
The repeated keys warning causes a lot of spam here (400+ warnings) as I have a lot of XAMLs that reference others (so completion etc works).

**Comment by batzen** [comment]
That sounds good.
Will improve the duplicate key warning to only appear if the content associated with the key differs.

**Comment by Nuklon** [comment]
> That sounds good. Will improve the duplicate key warning to only appear if the content associated with the key differs.

Great, that sounds perfect 🎉 Also thanks a lot for this tool, it's making a massive difference to overall UI performance 👍
