### ISSUE TITLE
Is there a way to specify the order of the files?

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#56]
Is there a way to specify the order of the files? I need to specify the merge order of some files manually
For example, the following code is merged like this

```
 <XAMLCombineItems Include="$(SharedPath)\Lang.xaml">
      <TargetFile>$(TargetFile)</TargetFile>
      <Visible>False</Visible>
    </XAMLCombineItems>
    <XAMLCombineItems Include="$(SharedPath)\Basic\*.xaml">
      <TargetFile>$(TargetFile)</TargetFile>
      <Visible>False</Visible>
    </XAMLCombineItems>
```

```
<Style x:Key="PathBaseStyle" TargetType="Path">
    <Setter Property="Stretch" Value="Uniform" />
    <Setter Property="SnapsToDevicePixels" Value="True" />
    <Setter Property="FlowDirection" Value="LeftToRight" />
  </Style>
  <system:Double x:Key="DefaultControlHeight">30</system:Double>
  <Thickness x:Key="DefaultControlPadding">10,6</Thickness>
  <Thickness x:Key="DefaultInputPadding">8,6</Thickness>
  <CornerRadius x:Key="DefaultCornerRadius">4</CornerRadius>
  <system:Double x:Key="{x:Static SystemParameters.VerticalScrollBarButtonHeightKey}">30</system:Double>
  <langs:LangProvider x:Key="Langs" />
  <SolidColorBrush o:Freeze="True" x:Key="LightPrimaryBrush" Color="{DynamicResource LightPrimaryColor}" />
  <LinearGradientBrush o:Freeze="True" x:Key="PrimaryBrush" EndPoint="1,0" StartPoint="0,0">
    <GradientStop o:Freeze="True" Color="{DynamicResource PrimaryColor}" Offset="0" />
    <GradientStop o:Freeze="True" Color="{DynamicResource DarkPrimaryColor}" Offset="1" />
  </LinearGradientBrush>
```

I expect the following code first
`<langs:LangProvider x:Key="Langs" />`

Then put other codes...

In previous versions, we could specify the order of the files using a text file
```
﻿# --------------------------------------
Lang.xaml
# --------------------------------------
Basic\Brushes.xaml
Basic\Converters.xaml
Basic\Effects.xaml
Basic\Fonts.xaml
Basic\Geometries.xaml
Basic\Paths.xaml
Basic\Sizes.xaml
Basic\Behaviors.xaml
# --------------------------------------
```

Is there a similar feature? can you add?

**Comment by batzen** [comment]
There is currently no way to specify the order.
The files are ordered by their path to ensure a deterministic result.

Why do you expect `<langs:LangProvider x:Key="Langs" />` to be the first?

**Comment by ghost1372** [comment]
> There is currently no way to specify the order. The files are ordered by their path to ensure a deterministic result.
> 
> Why do you expect `<langs:LangProvider x:Key="Langs" />` to be the first?

~~After using XAMLTools (I was using the old version before), users report various bugs, such as not changing the theme of the app~~
~~https://github.com/ghost1372/HandyControls/issues/158~~

~~The only thing that seems to be a problem is the order of the styles.
I would be very grateful if you could take a look at this issue~~

**Comment by ghost1372** [comment]
My issue was solved by Excluding a file.
However, having such a feature can be useful.
sorry for taking your time❤️
Thanks again for your useful tool

**Comment by batzen** [comment]
I decided not to allow to specify the order as this would conflict with automatic reordering for proper definition orders.
