### ISSUE TITLE
ResourceDictionary code behind

### ISSUE THREAD

**Issue by Myaukolka** [batzen/XAMLTools#77]
Is it possible to use your tool to merge resource dictionaries that have a `x:Class` directive pointing to code behind file? This is required to be able to use `EventSetter` in style definitions. Is there a workaround to define event handlers for styles without XAML otherwise?

**Comment by batzen** [comment]
@Myaukolka Sorry for my late response.

In theory that should work.
The only thing that might break is building the XAML files as is when in building, as that would generate duplicate code.
Which means you'd have to set `RemoveXAMLCombineItemsFromPages` to `true` always.

**Comment by Myaukolka** [comment]
Thank you @batzen for the reply and the `RemoveXAMLCombineItemsFromPages` hint!
This allows to use a single class containing all event handlers for all styles (as it's not possible to set `x:Class` attribute multiple times when merging, which makes sense). This does require to switch `RemoveXAMLCombineItemsFromPages` property to be able to see and edit individual style files from solution explorer and back to build the project, but it's a workaround i can live with.
I don't know if any better support for this use case is possible and it's probably not a very common one, but it would be great to have a more straightforward way to handle this.
Either way thank you very much for help and this great tool!

**Comment by batzen** [comment]
RemoveXAMLCombineItemsFromPages does not remove the items from the project view, it just doesn't add them as pages (xaml compile items), which causes intellisense to stop working in the individual files.

**Comment by Myaukolka** [comment]
Sorry I should've mentioned this is what's happening in JetBrains Rider 2022.3.1. Source resource dictionary files disappear from project view when `RemoveXAMLCombineItemsFromPages` set to true

**Comment by batzen** [comment]
Ah, Rider behaves a bit strange in this regard.
Just add
```
<None Include="Pattern for your files" />
```
to an ItemGroup inside your project and your files should re-appear.
