### ISSUE TITLE
XAML Node Stream: Missing StartObject before StartMember 

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#84]
Hi @batzen i am trying to merge all xaml files into a single xaml file ([this project](https://github.com/InkoreStudios/UI.WPF.Modern))
i am using this command:

```
<ItemGroup>
	<PackageReference Include="XAMLTools.MSBuild" Version="1.0.0-alpha0143">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>
<ItemGroup>
	<XAMLCombineItems Include="**\*.xaml" Exclude="Properties\DesignTimeResources.xaml;Themes\Theme.xaml;DensityStyles\Compact.xaml;DesignTime\DesignTimeResources.xaml;DesignTime\ResourceKeys.xaml;DesignTime\SystemColors.xaml;Schemes\Light.xaml;Schemes\Dark.xaml;Schemes\HighContrast.xaml">
		<TargetFile>Themes\Theme.xaml</TargetFile>
		<Visible>False</Visible>
	</XAMLCombineItems>
</ItemGroup>
```

but i am get this exception when i want to run my app:

```
System.Windows.Markup.XamlParseException: 'XAML Node Stream: Missing StartObject before StartMember '{http://schemas.microsoft.com/winfx/2006/xaml}_Initialization'.'
XamlObjectWriterException: XAML Node Stream: Missing StartObject before StartMember '{http://schemas.microsoft.com/winfx/2006/xaml}_Initialization'.
```

**Comment by batzen** [comment]
You can force XAMLCombine to include merged dictionaries via `ImportMergedResourceDictionaryReferences`.
Looking at your project show that you placed converters inside resource dictionaries inside nested merged dictionaries.
That's not required, as of my knowledge, and you might wanna change it as it only causes overhead.

Using `ImportMergedResourceDictionaryReferences` in your project would cause some element to be invalid as you are using relative paths in some places, which doesn't work with XAMLCombine.
You should always use the `component` syntax when defining the source for a merged dictionary.
More importantly you merge dictionaries that are already defined as combine items, which will cause further issues.

The best way to solve those issues is to just not nest converters in resource dictionaries.

The exclude pattern you are using
`Exclude="Properties\DesignTimeResources.xaml;Themes\Theme.xaml;DensityStyles\Compact.xaml;DesignTime\DesignTimeResources.xaml;DesignTime\ResourceKeys.xaml;DesignTime\SystemColors.xaml;Schemes\Light.xaml;Schemes\Dark.xaml;Schemes\HighContrast.xaml"`
should be
`Exclude="Properties\DesignTimeResources.xaml;Themes\Theme.xaml;Themes\DensityStyles\Compact.xaml;Themes\DesignTime\DesignTimeResources.xaml;Themes\DesignTime\ResourceKeys.xaml;Themes\DesignTime\SystemColors.xaml;Themes\Schemes\Light.xaml;Themes\Schemes\Dark.xaml;Themes\Schemes\HighContrast.xaml"`.

I don't want to educate you how to nest resources though.
I just want to point out that it won't work that way. ;-)

I don't get the exception you get when trying to start the SampleApp.
Did you start a different app?
It might be beneficial if you could create a branch in your repo where you try to integrate XAMLCombine.
Would be easier to see what's wrong in case you encounter more issues.

**Comment by ghost1372** [comment]
@batzen  thank you 
i tested localy in a private branch, so exclude pattern was true
however I found the cause of the problem 
The problem was in the checkbox control so i fixed it.

i have a question about 2 library merging so i want to create a new issue

**Comment by batzen** [comment]
Can we close this one then?

**Comment by ghost1372** [comment]
yes thank you
