### ISSUE TITLE
Win prefix added to all codes, why?

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#88]
Today I noticed that all codes have been prefixed with `Win:`
You can see my generated generic.xaml file here. Why this is happening??

https://github.com/WinUICommunity/WinUICommunity/blob/main/dev/Components/Themes/Generic.xaml

**Comment by batzen** [comment]
That's most likely the case because you define and use that prefix for the same namespace as the default one is in some of your sources and the.NET XML classes prefer the prefix then.
You should remove the explicit prefixed one and it should be gone in the generated file.

**Comment by ghost1372** [comment]
tnx fixed
i removed `xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation"`

```

xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
```
