### ISSUE TITLE
AOT Support

### ISSUE THREAD

**Issue by ghost1372** [batzen/XAMLTools#90]
Is this library compatible with AOT? If not, can you add support for it?
I've been having trouble with my libraries (when AOT publish) lately and this is when I used ResourcesDictionary and Xaml.Tools.

**Comment by batzen** [comment]
It's only used during compile time so there shouldn't be any need to be AOT compatible.
Which errors do you get exactly?

**Comment by ghost1372** [comment]
I realize that this has nothing to do with Xaml TooIs. I reported this bug to winui team. It seems that resource dictionary has some issues with aot (app crash due to can not finding resources)
